### ISSUE TITLE
Caching issue solution

### ISSUE THREAD

**Issue by zcream** [glewe/software-license-manager-class#2]
Hi @glewe with reference to your query on wordpress - https://wordpress.org/support/topic/verification-api-secret-key-is-invalid/ 

How did you solve this issue of server side caching ? Just wondering if I can add something in the curl code to ensure that the cache is cleared.

**Comment by glewe** [comment]
Hi @zcream ,
that is quite some time ago. As far as I remember, it was a local browser cache issue. Never had any problems since then.
Best regards
George

**Comment by zcream** [comment]
Thanks. It sorted itself out.
