### ISSUE TITLE
I can't achieve this in my project

### ISSUE THREAD

**Issue by Teelm-com** [glewe/software-license-manager-class#3]
something is wrong；SoftwareLicenseManager->show( $data = NULL, $showDetails = TRUE )；
Warning: count(): Parameter must be an array or an object that implements Countable in if (count($license_data->registered_domains)) {
                    foreach ($license_data->registered_domains as $domain) {
                        $domains .= $domain->registered_domain . ', ';
                    }
                    $domains = substr($domains, 0, -2);
                }

**Comment by glewe** [comment]
Hi @Teelm-com ,
the code in your error message does not reflect what is in the class. Are you using the latest version 1.1.1?
The show{} function contains this part:
```
    if (count($data->registered_domains)) {
        foreach ($data->registered_domains as $domain) {
            $domains .= $domain->registered_domain . ', ';
        }
        $domains = substr($domains, 0, -2); // Remove last comma and blank
    }
```
There is no $license_data variable. Did you check that?
Best regards,
George

**Comment by Teelm-com** [comment]
Yes, I am using the latest version 1.1.1, $license_data is modified according to my project.
![QQ截图20220601032051](https://user-images.githubusercontent.com/41373010/171269428-44cc3d11-0602-4726-8909-97392c19927b.png)

**Comment by glewe** [comment]
Hi @Teelm-com,
the class I am providing here does not contain a variable of that name. Die you define it in your code using my class? It seems you are passing an empty array to the show() method as the first parameter.
Best regards,
George

**Comment by glewe** [comment]
Expired
