### ISSUE TITLE
Using alert box

### ISSUE THREAD

**Issue by oleteacher** [glewe/software-license-manager-class#4]
Hey, great class thanks for sharing.

I cannot figure out how to use the `$alertBox`. 

I have tried calling with JavaScript without luck. Perhaps I do not understand how it is intended to function. Could you please review my Bootstrap code below and give a tip to get working?

```
<?php

require "slmclass.php";

$LIC = new SoftwareLicenseManager();

$LIC->setKey('63784eb44a771');
$LIC->load();

?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <title>Bootstrap 4 Page</title>
</head>
<body>

  <div class="container">
    <div class="row">
      <div class="col">
        <h1>Welcome to Our Page</h1>
        <p>
		
		<?php
			
			echo "<br>";
			echo $LIC->show($LIC->details, true);
			echo "<br>";
			if ($LIC->domainRegistered()) {
			  echo "This domain is registered"; 
			} else {
			  echo "This domain is not registered";
			}
			echo "<br>";
			$status = $LIC->status();
			if ($status == 'active') {
			  echo "License is active - we could forward to main page";
			} else {
			  echo "License is not active - we forward to error page";
			}
		?>
		
		</p>
                <button type="button" class="btn btn-primary" id="alertButton">Show Alert</button>

			<script>
				// Get button 
				var btn = document.getElementById("alertButton");

				// Handler for click event
				btn.addEventListener("click", function() {

				  // Get alert HTML
				  var alertBox = <?php echo $alertBox; ?>;
				  
				  // Create alert div
				  var alert = document.createElement('div');
			</script>
      </div>
    </div>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>
```

**Comment by glewe** [comment]
Hi @oleteacher ,
"alertBox" is a string value containing the HTML code of a Bootstrap alertbox. It contains quotes for attribute values. If you put that into a Javascript string variable it might become code that the browser cannot render.
Instead, try echo the alertBox from your PHP code.
I hope that helps.
Best regards,
G

**Comment by oleteacher** [comment]
Thanks for reply. Issue is; it does not work using template without JavaScript:

```
<?php

require "slmclass.php";

$LIC = new SoftwareLicenseManager();

$LIC->setKey('63784eb44a771');
$LIC->load();

?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <title>Bootstrap 4 Page</title>
</head>
<body>

  <div class="container">
    <div class="row">
      <div class="col">
        <h1>Welcome to Our Page</h1>
        <p>
		
		<?php
			
			echo "<br>";
			echo $LIC->show($LIC->details, true);
			echo "<br>";
			if ($LIC->domainRegistered()) {
			  echo "This domain is registered"; 
			} else {
			  echo "This domain is not registered";
			}
			echo "<br>";
			$status = $LIC->status();
			if ($status == 'active') {
			  echo "License is active - we could forward to main page";
			} else {
			  echo "License is not active - we forward to error page";
			}
		?>
		
		</p>

      </div>
    </div>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>
```

Do you have time to show me a working example? Just not getting it...

**Comment by glewe** [comment]
Hi @oleteacher ,

first, you should make sure that `$LIC->load()` returns a senseful response. It seems it does not in your case.

Then, add the following array initialization to the `show()` function of the class, like that:

```
  function show($data, $showDetails = false)
  {
    $alert = array();
    $alert['type'] = 'secondary';
    $alert['title'] = 'Unknown';
    $alert['subject'] = '';
    $alert['text'] = '';
    $alert['help'] = '';
    $details = "";
    ...
```
That should at least give the BS alert and some errors if there is no meaningful response from your license server.
I get this then
![Clipboard01](https://github.com/glewe/software-license-manager-class/assets/2099217/de9d6d92-d6f9-43b5-822b-b371e2692443)

**Comment by oleteacher** [comment]
I am not sure what you mean? My page is working fine:

![image](https://github.com/glewe/software-license-manager-class/assets/26278259/d3ed5537-9ff5-47ec-ac2c-460840bac993)

Or I should say working fine to display. I have taken the tips from your readme and used them. But cannot figure out how your alert popup works.

I will figure it out, thank you for your replies.

**Comment by glewe** [comment]
Oh, ok, my bad.
That was a misunderstanding then.
The BS Alert object is not a popup though. You would have to use a modal dialog or a toast message to have something pop up. 
Best regards,
George

**Comment by oleteacher** [comment]
Yea, guess I am confused what the $alertBox does. When I see the code below, I assumed with a close button that the alert was a popup:

`<button type="button" class="close" data-dismiss="alert" title="' . $this->lang['close_this_message'] . '"><i class="far fa-times-circle"></i></button>`

**Comment by glewe** [comment]
I see. It is confusing indeed.
The BS Alert allows to hide itself with such Close button:
https://getbootstrap.com/docs/4.0/components/alerts/
Best regards,
George
